# Generated by Django 4.1.3 on 2022-12-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tguser",
            old_name="tg_chat_id",
            new_name="chat_id",
        ),
        migrations.RemoveField(
            model_name="tguser",
            name="tg_user_id",
        ),
    ]
