# Generated by Django 4.1.3 on 2022-12-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_rename_tg_chat_id_tguser_chat_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tguser",
            name="username",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Username",
            ),
        ),
    ]
